spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/supermercado
spring.config.import=optional:file:.env[.properties]

spring.application.name=supermercado-api
spring.datasource.url=jdbc:postgresql://localhost:5432/supermercado
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.threads.virtual.enabled=true
management.endpoints.web.exposure.include=health,info,metrics
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

keycloak.base-url=http://localhost:7080
keycloak.realm=supermercado
keycloak.client-id=supermercado-backend
keycloak.client-secret=${KEYCLOAK_BACKEND_CLIENT_SECRET:}
spring.http.client.connect-timeout=3s
spring.http.client.read-timeout=5s

spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1s
spring.rabbitmq.listener.simple.retry.multiplier=2

payment.gateway.max-amount=1000.00
payment.reconciliation.interval-ms=30000
payment.reconciliation.stale-after=60s
