spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:7080/realms/supermercado}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:7080/realms/supermercado/protocol/openid-connect/certs}
spring.config.import=optional:file:.env[.properties]

spring.application.name=supermercado-api
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:supermercado}
spring.datasource.username=${POSTGRES_USER:supermercado}
spring.datasource.password=${POSTGRES_PASSWORD:supermercado}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5673}
spring.rabbitmq.username=${RABBITMQ_USER:supermercado}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:supermercado}

spring.threads.virtual.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN
management.endpoint.health.group.readiness.include=readinessState,db,rabbit
management.metrics.tags.application=supermercado-api
logging.pattern.level=%5p [%X{requestId:-}]
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

keycloak.base-url=${KEYCLOAK_BASE_URL:http://localhost:7080}
keycloak.realm=supermercado
keycloak.client-id=supermercado-backend
keycloak.client-secret=${KEYCLOAK_BACKEND_CLIENT_SECRET:supermercado-backend-secret}
spring.http.client.connect-timeout=3s
spring.http.client.read-timeout=5s

spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1s
spring.rabbitmq.listener.simple.retry.multiplier=2

payment.gateway.max-amount=1000.00
payment.reconciliation.interval-ms=30000
payment.reconciliation.stale-after=60s

springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.display-request-duration=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=500ms
cache.products.ttl=60s

spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.flyway.init-sqls=SET TIME ZONE 'UTC'
